# Generated by Django 6.0.4 on 2026-04-09 19:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DubbingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Мова озвучення',
                'verbose_name_plural': 'Мови озвучення',
                'db_table': 'dubbing_languages',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('anime', 'Аніме'), ('serial', 'Серіал'), ('movie', 'Фільм')], max_length=20)),
                ('release_year', models.SmallIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('episode_count', models.SmallIntegerField(default=0)),
                ('season_count', models.SmallIntegerField(default=0)),
                ('episode_duration', models.SmallIntegerField(blank=True, help_text='хвилини', null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('views_count', models.IntegerField(default=0)),
                ('reactions_count', models.IntegerField(default=0)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Медіа',
                'verbose_name_plural': 'Медіа',
                'db_table': 'media',
                'ordering': ['-views_count'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Студія',
                'verbose_name_plural': 'Студії',
                'db_table': 'studios',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('moderator', 'Модератор'), ('admin', 'Адміністратор')], default='user', max_length=20)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог адміна',
                'verbose_name_plural': 'Логи адміна',
                'db_table': 'admin_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Колекція',
                'verbose_name_plural': 'Колекції',
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_censored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myproject.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myproject.media')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.collection')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.media')),
            ],
            options={
                'db_table': 'collection_media',
                'unique_together': {('collection', 'media')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='media',
            field=models.ManyToManyField(blank=True, through='myproject.CollectionMedia', to='myproject.media'),
        ),
        migrations.CreateModel(
            name='MediaDubbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dubbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.dubbinglanguage')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.media')),
            ],
            options={
                'db_table': 'media_dubbing',
                'unique_together': {('media', 'dubbing')},
            },
        ),
        migrations.AddField(
            model_name='media',
            name='dubbing_languages',
            field=models.ManyToManyField(blank=True, through='myproject.MediaDubbing', to='myproject.dubbinglanguage'),
        ),
        migrations.CreateModel(
            name='MediaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.genre')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.media')),
            ],
            options={
                'db_table': 'media_genres',
                'unique_together': {('media', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(blank=True, through='myproject.MediaGenre', to='myproject.genre'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Спам'), ('offensive', 'Образливий контент'), ('spoiler', 'Спойлер'), ('misinformation', 'Дезінформація'), ('other', 'Інше')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('reviewed', 'Переглянуто'), ('resolved', 'Вирішено'), ('dismissed', 'Відхилено')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.comment')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myproject.media')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Скарга',
                'verbose_name_plural': 'Скарги',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.SmallIntegerField()),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='myproject.media')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезони',
                'db_table': 'seasons',
                'ordering': ['season_number'],
                'unique_together': {('media', 'season_number')},
            },
        ),
        migrations.AddField(
            model_name='media',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='myproject.studio'),
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('positive', 'Позитивна'), ('negative', 'Негативна')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='myproject.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реакція на коментар',
                'verbose_name_plural': 'Реакції на коментарі',
                'db_table': 'comment_reactions',
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MediaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='myproject.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Перегляд',
                'verbose_name_plural': 'Перегляди',
                'db_table': 'media_views',
                'indexes': [models.Index(fields=['media', 'viewed_at'], name='media_views_media_i_9b1c33_idx')],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.SmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='myproject.season')),
            ],
            options={
                'verbose_name': 'Епізод',
                'verbose_name_plural': 'Епізоди',
                'db_table': 'episodes',
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='UserMediaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Дивлюсь'), ('completed', 'Переглянуто'), ('on_hold', 'Призупинено'), ('dropped', 'Покинуто'), ('plan_to_watch', 'Планую')], default='plan_to_watch', max_length=20)),
                ('episodes_watched', models.SmallIntegerField(default=0)),
                ('user_rating', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='myproject.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус перегляду',
                'verbose_name_plural': 'Статуси перегляду',
                'db_table': 'user_media_status',
                'unique_together': {('user', 'media')},
            },
        ),
    ]
